categories: [Tools]
description: {{ cookiecutter.project_short_description }}
name: {{ cookiecutter.__pkg_name }}{{cookiecutter.__exec_hint}}
owner: {{ cookiecutter.toolrepo_username }}
exclude:
 - test-data/
 - .git/
 - .gitignore/
 - .gitmodules/
 - README.md
 - tool_test_output.html
 - tool_test_output.json
 - .python-version
 - job_conf_sample.yml
 - .setup_done
 - .testing
 - Makefile