name: Test {{cookiecutter.project_name}}

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
    
jobs:
  {{cookiecutter.pkg_name}}:
    runs-on: $\{\{ matrix.os \}\}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: {{cookiecutter.project_slug}}
          auto-activate-base: false

      - name: Setup Environment for {{cookiecutter.project_name}}
        run: |
          conda env create -f environment.yml
          conda activate {{cookiecutter.project_slug}}

      - name: Environment Information
        run: uname -a && env

      - name: Run Test Suite
        run: |
          {%- if cookiecutter.use_pytest == 'y' %}
          pytest
          {%- else %}
          python3 -m test
          {%- endif %}

      {%- if cookiecutter.project_shell_cmd %}
      - name: Test Usage and Version
        run: |
          {{cookiecutter.project_shell_cmd}} --help
          {{cookiecutter.project_shell_cmd}} --version

      - name: Test Actual Run
        run: |
          {{cookiecutter.project_shell_cmd}} # TODO
      {%- endif %}
